server:
  port: 8082

spring:
  application:
    name: ECOM-USER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/ecomuserdb
    username: ******
    password: *******

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  file:
    name: logs/AppLogs.log
  level:
    root: INFO
    com:
      deepak: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

info:
  app:
    name: ECOM-USER-SERVICE
    description: Ecommerce User Microservice
    version: 1.0.0